name: Publish build

on:
  push:
    branches:
      - experimental

jobs:
  publish:
    name: Upload build
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') == false

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Upload to Blob Builds
        uses: WalshyDev/blob-builds/gh-action@main
        with:
          project: Galactifun
          releaseChannel: 'Experimental'
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          file: ./build/libs/galactifun.jar
          releaseNotes: ${{ github.event.head_commit.message }}